version: '2'
services:
  react_front:
    container_name: react_front
    build:
      context: react-front
      dockerfile: Dockerfile
      args:
        - APP_HOME=/react_front
    environment:
      TZ: Asia/Tokyo
    volumes:
      - "./react-front:/react_front"
    ports:
      - "3000:3000"
    command: npm start
  sample_api:
    container_name: cuegent-sample_api
    build:
      context: ./sample_api
      dockerfile: Dockerfile
      args:
        - APP_HOME=/sample_api
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    command: rails s -p 3000 -b 0.0.0.0
    volumes:
      - ./sample_api:/sample_api
    ports:
      - "3001:3000"
